language: csharp

os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 2.0.0

services:
  - docker

script:
  - dotnet restore
  - dotnet build Polylines
  - dotnet test Polylines.Tests
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then
  dotnet pack Polylines --configuration Release /p:Version=$TRAVIS_TAG;
  nuget push Polylines/bin/Release/*.nupkg -ApiKey $API_KEY;
  fi"
